apiVersion: v1
kind: Pod
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  containers:
    - name: count
      image: busybox
      args:
        - /bin/sh
        - -c
        - >
          i=0;
          while true;
          do
            echo "$i: $(date)" >> /tmp/test.log;
            echo "$(date) INFO $i" >> /tmp/test.log;
            i=$((i+1));
            sleep 1;
          done
      volumeMounts:
        - name: tmplog
          mountPath: /tmp
    - name: filebeat
      image: ninech/openshift-filebeat:latest
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
      volumeMounts:
        - name: filebeat-config-volume
          mountPath: /filebeat/config
          readOnly: true
        - name: tmplog
          mountPath: /tmp
  volumes:
    - name: tmplog
      emptyDir: {}
    - name: filebeat-config-volume
      configMap:
        name: filebeat-config
